const letters = [
  { letter: "", points: null, count: 2 },
  { letter: "A", points: 1, count: 6 },
  { letter: "E", points: 1, count: 6 },
  { letter: "K", points: 1, count: 6 },
  { letter: "T", points: 1, count: 5 },
  { letter: "Á", points: 1, count: 4 },
  { letter: "L", points: 1, count: 4 },
  { letter: "N", points: 1, count: 4 },
  { letter: "R", points: 1, count: 4 },
  { letter: "I", points: 1, count: 3 },
  { letter: "M", points: 1, count: 3 },
  { letter: "O", points: 1, count: 3 },
  { letter: "S", points: 1, count: 3 },
  { letter: "B", points: 2, count: 3 },
  { letter: "D", points: 2, count: 3 },
  { letter: "G", points: 2, count: 3 },
  { letter: "Ó", points: 2, count: 3 },
  { letter: "É", points: 3, count: 3 },
  { letter: "H", points: 3, count: 2 },
  { letter: "SZ", points: 3, count: 2 },
  { letter: "V", points: 3, count: 2 },
  { letter: "F", points: 4, count: 2 },
  { letter: "GY", points: 4, count: 2 },
  { letter: "J", points: 4, count: 2 },
  { letter: "Ö", points: 4, count: 2 },
  { letter: "P", points: 4, count: 2 },
  { letter: "U", points: 4, count: 2 },
  { letter: "Ü", points: 4, count: 2 },
  { letter: "Z", points: 4, count: 2 },
  { letter: "C", points: 5, count: 1 },
  { letter: "Í", points: 5, count: 1 },
  { letter: "NY", points: 5, count: 1 },
  { letter: "CS", points: 7, count: 1 },
  { letter: "Ő", points: 7, count: 1 },
  { letter: "Ú", points: 7, count: 1 },
  { letter: "Ű", points: 7, count: 1 },
  { letter: "LY", points: 8, count: 1 },
  { letter: "ZS", points: 8, count: 1 },
  { letter: "TY", points: 10, count: 1 },
];

module.exports = letters;
